### PR TITLE
fix helpers transforming 

### PR DESCRIPTION
**Pull request by fuzhenn**
The previous pull request : #141 

Recreate the pr to set base to 3.x

### CODE REVIEW

**Comment by Andarist** [comment]
Released in 3.0.6

**Comment by Andarist** [comment]
@fuzhenn had to revert this, because it broke some builds. The issue is that what gets built as external helpers "in memory" module is again transformed with `external-helpers` plugin and this is causing troubles. 

I'm not sure if this can be fixed reliably in this plugin. You could just add a post-process custom plugin for your needs, smth like:
```js
import { transform } from 'babel-core';

function es3ify() {
  return {
    name: 'es3ify',

    transformBundle(code) {
      return transform(code, {
        babelrc: false,
        plugins: ['transform-proto-to-assign'],
      })
    }
  }
}
```

Keep in mind, that I have not tested this piece of code, should work though.

I would be happy to merge a new PR with a fix for your issue that would not break other builds - but as mentioned I have no idea if this is possible. If you figure it out though - let me know.

**Comment by fuzhenn** [comment]
For someone may be intersested:

Maybe I missed something, babel 7 still has this problem. After hours of struggling, didn't find a decent solution.

So I decide to fix `__proto__` by mighty `string.replace`. 🤣

Anyway `@babel/plugin-transform-proto-to-assign` is not consistent with ES6's class specification, this brings a chance to fix it on modern browsers rather than old IEs.

So here is my solution:

* Append `_defaults` in your code:
```js
function _defaults(obj, defaults) {
    var keys = Object.getOwnPropertyNames(defaults);
    for (vari = 0; i < keys.length; i++) {
        var key = keys[i];
        var value = Object.getOwnPropertyDescriptor(defaults, key);
        if (value && value.configurable && obj[key] === undefined) {
            Object.defineProperty(obj, key, value);
        }
    }
    return obj;
}
```

* transform `__proto__` to `_defaults` with IE11-:
```js
const transformed = code.replace('subClass.__proto__ = superClass;',
    'if (typeof document !== \'undefined\' && document.documentMode < 11) { _defaults(subClass, superClass); } else { subClass.__proto__ = superClass;}'
);
```

**Comment by Andarist** [comment]
@fuzhenn I've recently explained a little bit why this still might happen with babel@7, u can read more about it here - https://github.com/rollup/rollup-plugin-babel/issues/237#issuecomment-416065437

**Pull request merged**
