### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MirrorHuang**

### CODE REVIEW

**Comment by Andarist** [comment]
As mentioned at the beginning of this section:
> _This is not needed for Babel 7 - it knows automatically that Rollup understands ES modules & that it shouldn't use any module transform with it. The section below describes what needs to be done for Babel 6._

This described how to configure babel@6 so `'env'` is the correct preset there.

**Comment by MirrorHuang** [comment]
when i use 'env', it will show error which is `Cannot find module 'babel-preset-env' from ... Did you mean @babel/env`
Here is my package.json:
`"devDependencies": {
    "rollup": "^0.67.1",
    "rollup-plugin-babel": "^4.0.3"
  },
  "dependencies": {
    "@babel/core": "^7.1.6",
    "@babel/preset-env": "^7.1.6"
  }`

rollup.config.js:
`{
  input: 'src/scripts/main.js',
  output:{
  	file: 'build/js/main.min.js',
  	format: 'umd',
  	sourceMap: true
  },
  plugins: [
    babel({
    	babelrc: false,
      exclude: 'node_modules/**',// 只编译我们的源代码
      presets: [['.jenv', { modules: false }]],
    }),
  ],
};`

**Comment by MirrorHuang** [comment]
> As mentioned at the beginning of this section:
> 
> > _This is not needed for Babel 7 - it knows automatically that Rollup understands ES modules & that it shouldn't use any module transform with it. The section below describes what needs to be done for Babel 6._
> 
> This described how to configure babel@6 so `'env'` is the correct preset there.

when i use 'env', it will show error which is Cannot find module 'babel-preset-env' from ... Did you mean @babel/env
Here is my package.json:
"devDependencies": { "rollup": "^0.67.1", "rollup-plugin-babel": "^4.0.3" }, "dependencies": { "@babel/core": "^7.1.6", "@babel/preset-env": "^7.1.6" }

rollup.config.js:
{ input: 'src/scripts/main.js', output:{ file: 'build/js/main.min.js', format: 'umd', sourceMap: true }, plugins: [ babel({ babelrc: false, exclude: 'node_modules/**',// 只编译我们的源代码 presets: [['env', { modules: false }]], }), ], };

**Comment by Andarist** [comment]
You are using babel@7, and you should use `@babel/env`. The section you have edited was describing how to configure things correctly when using babel@6.

**Pull request closed without merging**
