### PR TITLE
Upgrade babel and tweak according changes

### PR DESCRIPTION
**Pull request by TrySound**
- simplified preflight check for runtime helpers
- removed moduleName test
- tweaked removed options

### CODE REVIEW

**Comment by TrySound** [comment]
Not sure what fails. Looks like npm sucks again.

**Comment by Andarist** [comment]
You've updated package.json without updating the lock file - it seems to be a reason why CI fails. Could you amend ur PR with updated lock?

**Comment by TrySound** [comment]
Weird, npm-check didn't update lockfile like before.

**Comment by TrySound** [comment]
Done

**Pull request merged**
